general:
  seed: 42
  root_dir: graph-pes-results
  run_id: bespoke-train-1
  log_level: INFO
  progress: logged
  torch:
    dtype: float32
    float32_matmul_precision: high
fitting:
  pre_fit_model: true
  max_n_pre_fit: 5000
  trainer_kwargs:
    max_epochs: 250
    accelerator: auto
    enable_model_summary: false
    check_val_every_n_epoch: 10
  loader_kwargs:
    num_workers: 4
    persistent_workers: true
    batch_size: 16
    pin_memory: false
  keep: best
  callbacks: []
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 10
  swa: null
  early_stopping:
    patience: 10
  auto_fit_reference_energies: false
  lr_warmup_steps: null
  early_stopping_patience: null
  optimizer:
    name: AdamW
    lr: 0.01
wandb: null
CUTOFF: 3.7
model:
  offset: +LearnableOffset()
  many-body:
    +MACE:
      elements:
      - C
      cutoff: 3.7
      channels: 64
      layers: 2
      correlation: 3
      l_max: 2
      n_radial: 8
data:
  train:
    path: train.xyz
    shuffle: true
    cutoff: 3.7
  valid:
    path: valid.xyz
    cutoff: 3.7
  test:
    path: test.xyz
    cutoff: 3.7
loss:
- +PerAtomEnergyLoss()
- +ForceRMSE()
model_path: !!python/object/apply:pathlib.PosixPath
- graph-pes-results
- bespoke-train-1
- model.pt
lammps_model_path: !!python/object/apply:pathlib.PosixPath
- graph-pes-results
- bespoke-train-1
- lammps_model.pt
